# Generated by Django 5.1.7 on 2025-03-24 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_usereducation_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ish_joyi', models.CharField(max_length=255)),
                ('nomi', models.CharField(max_length=255)),
                ('lavozimi', models.CharField(max_length=255)),
                ('ishga_kirgan_yili', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='usereducation',
            name='user',
        ),
        migrations.CreateModel(
            name='Extra_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ish_joyi', models.CharField(max_length=255)),
                ('nomi', models.CharField(max_length=255)),
                ('lavozimi', models.CharField(max_length=255)),
                ('ishga_kirgan_yili', models.DateField()),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='accounts.experience')),
            ],
        ),
    ]
