# Generated by Django 5.0.13 on 2025-04-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_doctorprofile_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='salary',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
