# Generated by Django 5.1.3 on 2025-04-05 10:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_doctorprofile_salary"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DoctorProfile",
        ),
    ]
